### ISSUE TITLE
Cannot load `active_support/core_ext/string/inflections` for cask 'dracula-wallpaper'

### ISSUE THREAD

**Issue by schradert** [dracula/homebrew-install#16]
```bash
brew tap dracula/install
brew install --debug --verbose --cask dracula-wallpaper
```

Gives me:

```bash
❯ brew tap dracula/install
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 142 (delta 33), reused 50 (delta 23), pack-reused 68
Receiving objects: 100% (142/142), 28.37 KiB | 7.09 MiB/s, done.
Resolving deltas: 100% (55/55), done.
Tapped 1 command, 15 casks and 1 formula (34 files, 61.8KB).
❯ brew install --debug --verbose --cask dracula-wallpaper
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading dracula-wallpaper
Warning: Cask 'dracula-wallpaper' is unreadable: cannot load such file -- active_support/core_ext/string/inflections
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading dracula-wallpaper
==> Searching for similarly named casks...
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-wallpaper
Error: Cask 'dracula-wallpaper' is unreadable: cannot load such file -- active_support/core_ext/string/inflections
/opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-wallpaper.rb:1:in `require'
/opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-wallpaper.rb:1:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:133:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:133:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:225:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:516:in `load'
/opt/homebrew/Library/Homebrew/search.rb:98:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:97:in `map'
/opt/homebrew/Library/Homebrew/search.rb:97:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:117:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/install.rb:383:in `rescue in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:166:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `public_send'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

Not sure what other information is useful, but I'm on Homebrew version `4.2.15`

**Comment by luiscachog** [comment]
Same issue here when I'm doing a simple `search`, here is the output:

```
brew search --debug --verbose dracula
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromNameLoader): loading dracula-git
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromTapLoader): loading dracula/install/dracula-git
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FromAPILoader): loading emacs-dracula
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-ableton-live
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-alfred
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-betterdiscord
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-colorslurp
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-drafts
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-gitkraken
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-insomnia
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-lsd
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-macos-color-picker
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-mailspring
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-snippetslab
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-steam
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-terminal
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromTapLoader): loading dracula/install/dracula-wallpaper
Error: Cask 'dracula-wallpaper' is unreadable: cannot load such file -- active_support/core_ext/string/inflections
/opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-wallpaper.rb:1:in `require'
/opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-wallpaper.rb:1:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:133:in `instance_eval'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:133:in `load'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:225:in `load'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:517:in `load'
/opt/homebrew/Library/Homebrew/search.rb:96:in `block in search_casks'
/opt/homebrew/Library/Homebrew/search.rb:95:in `map'
/opt/homebrew/Library/Homebrew/search.rb:95:in `search_casks'
/opt/homebrew/Library/Homebrew/search.rb:115:in `search_names'
/opt/homebrew/Library/Homebrew/cmd/search.rb:81:in `run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11372/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```
