### ISSUE TITLE
Error when trying to brew tap

### ISSUE THREAD

**Issue by alex5517** [dracula/homebrew-install#2]
I am getting the following error when trying to run: `brew tap dracula/install`

I am running on a Macbook Pro 2021 with Apple M1 pro chip.
MacOS version: Monterey - Version 12.5.1
```
brew --version
Homebrew 3.5.10-64-gac94ca6
Homebrew/homebrew-core (git revision 9acc89c94e5; last commit 2022-08-30)
Homebrew/homebrew-cask (git revision bf973e39a8; last commit 2022-08-30)
```

```
ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
```

```
brew tap dracula/install --debug
/opt/homebrew/Library/Homebrew/shims/shared/git --version
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 19 (delta 1), reused 11 (delta 0), pack-reused 6
Receiving objects: 100% (19/19), 8.77 KiB | 8.77 MiB/s, done.
Resolving deltas: 100% (1/1), done.
2022-08-30 05:48:52.458 defaults[9066:34850]
The domain/default pair of (com.runningwithcrayons.Alfred-Preferences, syncfolder) does not exist
Error: Invalid cask: /opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-drafts.rb
Cask 'dracula-drafts' is unreadable: undefined method `/' for nil:NilClass
Error: Cannot tap dracula/install: invalid syntax in tap!
/opt/homebrew/Library/Homebrew/tap.rb:312:in `install'
/opt/homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by mauvehed** [comment]
Same issue on my M1 MacStudio w/ MacOS 12.15.1

`brew --version
Homebrew 3.5.10
Homebrew/homebrew-core (git revision 510a8caa26c; last commit 2022-09-03)
Homebrew/homebrew-cask (git revision d7b9e451b0; last commit 2022-09-04) `

`ruby --version
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21] `

`brew tap dracula/install
==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 19 (delta 1), reused 11 (delta 0), pack-reused 6
Receiving objects: 100% (19/19), 8.77 KiB | 4.39 MiB/s, done.
Resolving deltas: 100% (1/1), done.
2022-09-03 13:06:59.621 defaults[37542:11702927] 
The domain/default pair of (com.runningwithcrayons.Alfred-Preferences, syncfolder) does not exist
Error: Invalid cask: /opt/homebrew/Library/Taps/dracula/homebrew-install/Casks/dracula-drafts.rb
Cask 'dracula-drafts' is unreadable: undefined method `/' for nil:NilClass
Error: Cannot tap dracula/install: invalid syntax in tap! `

**Comment by danielbayley** [comment]
Seems to be a problem on Apple silicon macs… Unfortunately, I don’t currently have access to one! However, I just pushed a potential fix… @alex5517 @mauvehed Please can you test?

**Comment by alex5517** [comment]
Bit better.

`➜ ~ brew tap dracula/install
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 99682c5af to c49f2e8b4.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
rome                                                          sambamba
==> New Casks
random-mouse-clicker

You have 15 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Tapping dracula/install
Cloning into '/opt/homebrew/Library/Taps/dracula/homebrew-install'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 23 (delta 4), reused 15 (delta 3), pack-reused 6
Receiving objects: 100% (23/23), 9.13 KiB | 9.13 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Tapped 1 command and 11 casks (26 files, 31.0KB).`

But fails to install dracula-macos-color-picker

`➜ ~ brew install --cask dracula-macos-color-picker
==> Downloading https://github.com/dracula/macos-color-picker/archive/refs/heads/main.zip
==> Downloading from https://codeload.github.com/dracula/macos-color-picker/zip/refs/heads/main
##=O#- #
Warning: No checksum defined for cask 'dracula-macos-color-picker', skipping verification.
==> Installing Cask dracula-macos-color-picker
/opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:1:in `require': cannot load such file -- active_support/all (LoadError)
	from /opt/homebrew/Library/Taps/dracula/homebrew-install/cmd/dracula-yaml-json.rb:1:in `<top (required)>'
	from ./generate.command:4:in `require'
	from ./generate.command:4:in `<main>'
==> Purging files for version latest of Cask dracula-macos-color-picker
Error: It seems the Generic Artifact source '/opt/homebrew/Caskroom/dracula-macos-color-picker/latest/macos-color-picker-main/Dracula.clr' is not there.`
